In [246]:
import pandas as pd
import numpy as np

In [112]:
df = pd.read_csv("energy_sources_state.csv")

In [113]:
df.head()

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,2017F,AK,ABICB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,-14.0,-4.0,0.0,0.0,-5.0,-2.0,-3.0,-3.0,-2.0
1,2017F,AK,ARICB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,547.0,10198.0,12644.0,14931.0,14343.0,12763.0,12335.0,12450.0,12365.0,13561.0
2,2017F,AK,ARTCB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,547.0,10198.0,12644.0,14931.0,14343.0,12763.0,12335.0,12450.0,12365.0,13561.0
3,2017F,AK,ARTXB,312.0,555.0,489.0,589.0,791.0,878.0,1646.0,...,547.0,10198.0,12644.0,14931.0,14343.0,12763.0,12335.0,12450.0,12365.0,13561.0
4,2017F,AK,AVACB,5209.0,6441.0,5202.0,3273.0,2319.0,1478.0,1086.0,...,1008.0,1095.0,854.0,801.0,776.0,701.0,658.0,317.0,137.0,214.0

In [185]:
#msn_codes = {"NNTCB":"Natural Gas", "CLTCB": "Coal", "MMTCB": "Motor Gas excl Ethanol", "DFTCB": "Distillate Fuel Oil",
            #"JFTCB": "Jet Fuel", "HLTCB": "HGL", "RFTCB": "Residual Fueal", "P1TCB": "Other Petroleum",
            #"NUETB": "Nuclear Electric Power", "HYTCB": "Hydroelectric Power", "BMTCB": "Biomass",
            #"RETCB": "Other Renewables"}

In [186]:
#energy_types = pd.DataFrame()

In [191]:
#for key,value in msn_codes.items():
    #new_df = df.loc[df.MSN==key]
    #energy_types = energy_types.append(new_df)
    #energy_type = value
    #msn = key
    #print(energy_type)
    
    #for index,row in new_df.iterrows():
        #if new_df["MSN"] == msn:
        #new_df["Energy_Type"] = energy_type
        #energy_types = energy_types.append(new_df)

In [171]:
energy_types_state = df.loc[(df.MSN=="NNTCB") | (df.MSN=="CLTCB") | (df.MSN=="MMTCB") | (df.MSN=="DFTCB") | (df.MSN=="JFTCB")
                           | (df.MSN=="HLTCB") | (df.MSN=="RFTCB") | (df.MSN=="P1TCB") | (df.MSN=="NUETB")
                           | (df.MSN=="HYTCB") | (df.MSN=="BMTCB") | (df.MSN=="RETCB")]

In [172]:
energy_types_state.head(15)

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
7,2017F,AK,BMTCB,3681.0,4145.0,4246.0,4383.0,4728.0,4863.0,5035.0,...,1233.0,2543.0,2704.0,2675.0,2263.0,3357.0,3522.0,7488.0,8093.0,7023.0
19,2017F,AK,CLTCB,7189.0,11552.0,13559.0,11999.0,12029.0,9888.0,16431.0,...,14705.0,14505.0,14548.0,15481.0,15521.0,14819.0,18225.0,19511.0,16613.0,16376.0
27,2017F,AK,DFTCB,15354.0,17023.0,17412.0,18196.0,20441.0,22066.0,23805.0,...,75258.0,83571.0,79470.0,84569.0,79460.0,73218.0,73108.0,78162.0,64261.0,59052.0
63,2017F,AK,HLTCB,176.0,311.0,214.0,304.0,328.0,350.0,378.0,...,1277.0,1555.0,1371.0,1279.0,1299.0,1257.0,1265.0,1094.0,1165.0,1240.0
68,2017F,AK,HYTCB,3120.0,3168.0,3207.0,3410.0,3374.0,3655.0,3293.0,...,11547.0,12920.0,13982.0,13066.0,14988.0,13696.0,14633.0,14621.0,15317.0,15143.0
75,2017F,AK,JFTCB,10632.0,12803.0,15493.0,15800.0,16395.0,16517.0,20621.0,...,135044.0,106292.0,128857.0,118226.0,113205.0,107338.0,96006.0,102899.0,104844.0,100500.0
98,2017F,AK,MMTCB,8702.0,9514.0,10059.0,10529.0,10918.0,12868.0,10057.0,...,34251.0,34135.0,34846.0,33634.0,33718.0,32797.0,34213.0,34782.0,35217.0,34250.0
108,2017F,AK,NNTCB,2034.0,2300.0,4048.0,5567.0,6805.0,7670.0,12282.0,...,343938.0,343971.0,334978.0,339819.0,347228.0,332631.0,329274.0,333936.0,330883.0,343908.0
110,2017F,AK,NUETB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
115,2017F,AK,P1TCB,6076.0,7276.0,6055.0,5892.0,5038.0,4365.0,4716.0,...,30429.0,36379.0,42378.0,44833.0,40227.0,37003.0,32619.0,27883.0,27774.0,29128.0
141,2017F,AK,RETCB,6800.0,7313.0,7453.0,7793.0,8102.0,8519.0,8328.0,...,12913.0,15685.0,16965.0,16078.0,17796.0,18629.0,19790.0,23786.0,25174.0,23677.0
146,2017F,AK,RFTCB,4472.0,4081.0,4519.0,4708.0,5010.0,5539.0,6078.0,...,2465.0,3454.0,2158.0,1897.0,2719.0,593.0,750.0,731.0,0.0,0.0
209,2017F,AL,BMTCB,45681.0,46171.0,45959.0,45764.0,46341.0,47641.0,49102.0,...,176472.0,151086.0,180391.0,191327.0,192362.0,209069.0,200364.0,187987.0,187447.0,188663.0
221,2017F,AL,CLTCB,395400.0,382455.0,427177.0,442465.0,459000.0,533142.0,583457.0,...,842826.0,630969.0,718684.0,651032.0,547004.0,565051.0,575912.0,494311.0,410168.0,378890.0
229,2017F,AL,DFTCB,31413.0,25250.0,28903.0,29949.0,34403.0,30587.0,29948.0,...,152438.0,139850.0,147986.0,155442.0,156621.0,145092.0,143410.0,153651.0,169094.0,163537.0

In [199]:
working = energy_types_state
working.head()

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
7,2017F,AK,BMTCB,3681.0,4145.0,4246.0,4383.0,4728.0,4863.0,5035.0,...,2543.0,2704.0,2675.0,2263.0,3357.0,3522.0,7488.0,8093.0,7023.0,Biomass
19,2017F,AK,CLTCB,7189.0,11552.0,13559.0,11999.0,12029.0,9888.0,16431.0,...,14505.0,14548.0,15481.0,15521.0,14819.0,18225.0,19511.0,16613.0,16376.0,Coal
27,2017F,AK,DFTCB,15354.0,17023.0,17412.0,18196.0,20441.0,22066.0,23805.0,...,83571.0,79470.0,84569.0,79460.0,73218.0,73108.0,78162.0,64261.0,59052.0,Distillate Fuel Oil
63,2017F,AK,HLTCB,176.0,311.0,214.0,304.0,328.0,350.0,378.0,...,1555.0,1371.0,1279.0,1299.0,1257.0,1265.0,1094.0,1165.0,1240.0,HGL
68,2017F,AK,HYTCB,3120.0,3168.0,3207.0,3410.0,3374.0,3655.0,3293.0,...,12920.0,13982.0,13066.0,14988.0,13696.0,14633.0,14621.0,15317.0,15143.0,Hydroelectric Power

In [237]:
msn_codes = {"NNTCB":"Natural Gas", "CLTCB": "Coal", "MMTCB": "Motor Gas excl Ethanol", "DFTCB": "Distillate Fuel Oil",
            "JFTCB": "Jet Fuel", "HLTCB": "HGL", "RFTCB": "Residual Fueal", "P1TCB": "Other Petroleum",
            "NUETB": "Nuclear Electric Power", "HYTCB": "Hydroelectric Power", "BMTCB": "Biomass",
            "RETCB": "Total Renewables"}

In [238]:
for key,value in msn_codes.items():
    energy_type = value
    working.loc[(working.MSN == key),'Energy_Type']=energy_type
    #print(energy_type)

In [239]:
working.head()

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
7,2017F,AK,BMTCB,3681.0,4145.0,4246.0,4383.0,4728.0,4863.0,5035.0,...,2543.0,2704.0,2675.0,2263.0,3357.0,3522.0,7488.0,8093.0,7023.0,Biomass
19,2017F,AK,CLTCB,7189.0,11552.0,13559.0,11999.0,12029.0,9888.0,16431.0,...,14505.0,14548.0,15481.0,15521.0,14819.0,18225.0,19511.0,16613.0,16376.0,Coal
27,2017F,AK,DFTCB,15354.0,17023.0,17412.0,18196.0,20441.0,22066.0,23805.0,...,83571.0,79470.0,84569.0,79460.0,73218.0,73108.0,78162.0,64261.0,59052.0,Distillate Fuel Oil
63,2017F,AK,HLTCB,176.0,311.0,214.0,304.0,328.0,350.0,378.0,...,1555.0,1371.0,1279.0,1299.0,1257.0,1265.0,1094.0,1165.0,1240.0,HGL
68,2017F,AK,HYTCB,3120.0,3168.0,3207.0,3410.0,3374.0,3655.0,3293.0,...,12920.0,13982.0,13066.0,14988.0,13696.0,14633.0,14621.0,15317.0,15143.0,Hydroelectric Power

In [240]:
working.columns

Index(['Data_Status', 'State', 'MSN', '1960', '1961', '1962', '1963', '1964',
       '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973',
       '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       'Energy_Type'],
      dtype='object')

In [241]:
final = working.drop(["Data_Status"], axis=1)

In [242]:
final.head()

,State,MSN,1960,1961,1962,1963,1964,1965,1966,1967,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
7,AK,BMTCB,3681.0,4145.0,4246.0,4383.0,4728.0,4863.0,5035.0,4671.0,...,2543.0,2704.0,2675.0,2263.0,3357.0,3522.0,7488.0,8093.0,7023.0,Biomass
19,AK,CLTCB,7189.0,11552.0,13559.0,11999.0,12029.0,9888.0,16431.0,18462.0,...,14505.0,14548.0,15481.0,15521.0,14819.0,18225.0,19511.0,16613.0,16376.0,Coal
27,AK,DFTCB,15354.0,17023.0,17412.0,18196.0,20441.0,22066.0,23805.0,25940.0,...,83571.0,79470.0,84569.0,79460.0,73218.0,73108.0,78162.0,64261.0,59052.0,Distillate Fuel Oil
63,AK,HLTCB,176.0,311.0,214.0,304.0,328.0,350.0,378.0,406.0,...,1555.0,1371.0,1279.0,1299.0,1257.0,1265.0,1094.0,1165.0,1240.0,HGL
68,AK,HYTCB,3120.0,3168.0,3207.0,3410.0,3374.0,3655.0,3293.0,3786.0,...,12920.0,13982.0,13066.0,14988.0,13696.0,14633.0,14621.0,15317.0,15143.0,Hydroelectric Power

In [261]:
final = final.reset_index()

In [262]:
final.head(15)

,index,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
0,7,AK,BMTCB,3681.0,4145.0,4246.0,4383.0,4728.0,4863.0,5035.0,...,2543.0,2704.0,2675.0,2263.0,3357.0,3522.0,7488.0,8093.0,7023.0,Biomass
1,19,AK,CLTCB,7189.0,11552.0,13559.0,11999.0,12029.0,9888.0,16431.0,...,14505.0,14548.0,15481.0,15521.0,14819.0,18225.0,19511.0,16613.0,16376.0,Coal
2,27,AK,DFTCB,15354.0,17023.0,17412.0,18196.0,20441.0,22066.0,23805.0,...,83571.0,79470.0,84569.0,79460.0,73218.0,73108.0,78162.0,64261.0,59052.0,Distillate Fuel Oil
3,63,AK,HLTCB,176.0,311.0,214.0,304.0,328.0,350.0,378.0,...,1555.0,1371.0,1279.0,1299.0,1257.0,1265.0,1094.0,1165.0,1240.0,HGL
4,68,AK,HYTCB,3120.0,3168.0,3207.0,3410.0,3374.0,3655.0,3293.0,...,12920.0,13982.0,13066.0,14988.0,13696.0,14633.0,14621.0,15317.0,15143.0,Hydroelectric Power
5,75,AK,JFTCB,10632.0,12803.0,15493.0,15800.0,16395.0,16517.0,20621.0,...,106292.0,128857.0,118226.0,113205.0,107338.0,96006.0,102899.0,104844.0,100500.0,Jet Fuel
6,98,AK,MMTCB,8702.0,9514.0,10059.0,10529.0,10918.0,12868.0,10057.0,...,34135.0,34846.0,33634.0,33718.0,32797.0,34213.0,34782.0,35217.0,34250.0,Motor Gas excl Ethanol
7,108,AK,NNTCB,2034.0,2300.0,4048.0,5567.0,6805.0,7670.0,12282.0,...,343971.0,334978.0,339819.0,347228.0,332631.0,329274.0,333936.0,330883.0,343908.0,Natural Gas
8,110,AK,NUETB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Nuclear Electric Power
9,115,AK,P1TCB,6076.0,7276.0,6055.0,5892.0,5038.0,4365.0,4716.0,...,36379.0,42378.0,44833.0,40227.0,37003.0,32619.0,27883.0,27774.0,29128.0,Other Petroleum
10,141,AK,RETCB,6800.0,7313.0,7453.0,7793.0,8102.0,8519.0,8328.0,...,15685.0,16965.0,16078.0,17796.0,18629.0,19790.0,23786.0,25174.0,23677.0,Total Renewables
11,146,AK,RFTCB,4472.0,4081.0,4519.0,4708.0,5010.0,5539.0,6078.0,...,3454.0,2158.0,1897.0,2719.0,593.0,750.0,731.0,0.0,0.0,Residual Fueal
12,209,AL,BMTCB,45681.0,46171.0,45959.0,45764.0,46341.0,47641.0,49102.0,...,151086.0,180391.0,191327.0,192362.0,209069.0,200364.0,187987.0,187447.0,188663.0,Biomass
13,221,AL,CLTCB,395400.0,382455.0,427177.0,442465.0,459000.0,533142.0,583457.0,...,630969.0,718684.0,651032.0,547004.0,565051.0,575912.0,494311.0,410168.0,378890.0,Coal
14,229,AL,DFTCB,31413.0,25250.0,28903.0,29949.0,34403.0,30587.0,29948.0,...,139850.0,147986.0,155442.0,156621.0,145092.0,143410.0,153651.0,169094.0,163537.0,Distillate Fuel Oil

In [306]:
state_list = final["State"].unique().tolist()
state_list

['AK',
 'AL',
 'AR',
 'AZ',
 'CA',
 'CO',
 'CT',
 'DC',
 'DE',
 'FL',
 'GA',
 'HI',
 'IA',
 'ID',
 'IL',
 'IN',
 'KS',
 'KY',
 'LA',
 'MA',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MS',
 'MT',
 'NC',
 'ND',
 'NE',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OK',
 'OR',
 'PA',
 'RI',
 'SC',
 'SD',
 'TN',
 'TX',
 'US',
 'UT',
 'VA',
 'VT',
 'WA',
 'WI',
 'WV',
 'WY']

In [254]:
final.columns

Index(['State', 'MSN', '1960', '1961', '1962', '1963', '1964', '1965', '1966',
       '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975',
       '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', 'Energy_Type'],
      dtype='object')

In [265]:
year_list = ['1960']#, '1961', '1962', '1963', '1964', '1965', '1966',
       #'1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975',
       #'1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       #'1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       #'1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       #'2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       #'2012', '2013', '2014', '2015', '2016', '2017']
state_list = ["IN"]

In [304]:
calculated = []
for state in state_list:
    state_df = final.loc[final["State"]== state]
    for year in year_list:
        state_year = state_df[year]
        state_values = state_year.iloc[0:12].tolist()
        renew = state_values[10]
        total_renewable = renew[0]
        bio = state_values[0]
        biomass = bio[0]
        hydro = state_values[4]
        hydroelectric = hydro[0]
        other_renewable = total_renewable-biomass-hydroelectric
        calculated.append()

TypeError: 'float' object is not subscriptable

In [305]:
calculated

[]

In [276]:
indiana = final.loc[final["State"]=="IN"]
indiana.head(12)

,index,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
180,3037,IN,BMTCB,23477.0,23062.0,23293.0,23463.0,22696.0,22081.0,23325.0,...,94504.0,102130.0,108555.0,105085.0,109610.0,114594.0,119075.0,121212.0,119034.0,Biomass
181,3049,IN,CLTCB,794942.0,798090.0,785052.0,815496.0,860401.0,900562.0,967518.0,...,1365413.0,1449371.0,1333442.0,1193465.0,1198611.0,1221492.0,1007472.0,948386.0,929271.0,Coal
182,3057,IN,DFTCB,149743.0,149015.0,150655.0,150887.0,150955.0,151149.0,150689.0,...,201056.0,212698.0,224114.0,220280.0,238035.0,251982.0,245348.0,234610.0,214550.0,Distillate Fuel Oil
183,3093,IN,HLTCB,21990.0,21138.0,23133.0,25967.0,20791.0,25453.0,29525.0,...,30120.0,26223.0,25996.0,20841.0,25245.0,24497.0,19845.0,18445.0,17844.0,HGL
184,3098,IN,HYTCB,1079.0,1137.0,796.0,544.0,472.0,979.0,990.0,...,4914.0,4426.0,3972.0,4125.0,3692.0,3530.0,3553.0,3935.0,2820.0,Hydroelectric Power
185,3105,IN,JFTCB,7127.0,7751.0,8981.0,9855.0,10321.0,10161.0,10509.0,...,42255.0,43109.0,51237.0,48301.0,46721.0,46653.0,46383.0,50198.0,55114.0,Jet Fuel
186,3128,IN,MMTCB,229006.0,228155.0,236014.0,240667.0,242522.0,252413.0,263793.0,...,352845.0,355600.0,339463.0,336288.0,340239.0,339865.0,353481.0,357193.0,355608.0,Motor Gas excl Ethanol
187,3138,IN,NNTCB,219758.0,248273.0,281781.0,297815.0,333685.0,357502.0,399896.0,...,511289.0,577423.0,635117.0,654528.0,680051.0,723942.0,735055.0,779945.0,747968.0,Natural Gas
188,3140,IN,NUETB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Nuclear Electric Power
189,3145,IN,P1TCB,110580.0,110182.0,117141.0,119993.0,124162.0,126310.0,128358.0,...,121761.0,103922.0,101295.0,86738.0,102507.0,100758.0,112544.0,95012.0,88852.0,Other Petroleum
190,3171,IN,RETCB,24556.0,24199.0,24089.0,24007.0,23168.0,23060.0,24315.0,...,117153.0,139723.0,149114.0,144588.0,151650.0,157222.0,171064.0,177417.0,176422.0,Total Renewables
191,3176,IN,RFTCB,82209.0,76989.0,67415.0,67886.0,71577.0,81939.0,76316.0,...,1492.0,1284.0,1574.0,1416.0,926.0,905.0,1064.0,1739.0,3631.0,Residual Fueal

In [218]:
us_df = pd.read_csv("energy_sources_us.csv")
us_df.head()

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,2017F,US,ABICB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,96.0,-793.0,-242.0,10.0,-5.0,-379.0,-141.0,-348.0,-293.0,-192.0
1,2017F,US,ABICP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,19.0,-157.0,-48.0,2.0,-1.0,-75.0,-28.0,-69.0,-58.0,-38.0
2,2017F,US,ARICB,733782.0,753551.0,803533.0,824642.0,840781.0,890266.0,935557.0,...,1011970.0,873085.0,877770.0,859488.0,826700.0,783347.0,792637.0,831663.0,853363.0,849182.0
3,2017F,US,ARICP,110576.0,113555.0,121087.0,124268.0,126700.0,134157.0,140982.0,...,152497.0,131568.0,132274.0,129519.0,124578.0,118045.0,119445.0,125326.0,128596.0,127966.0
4,2017F,US,ARTCB,733782.0,753551.0,803533.0,824642.0,840781.0,890266.0,935557.0,...,1011970.0,873085.0,877770.0,859488.0,826700.0,783347.0,792637.0,831663.0,853363.0,849182.0

In [222]:
energy_types_us = us_df.loc[(us_df.MSN=="NNTCB") | (us_df.MSN=="CLTCB") | (us_df.MSN=="MMTCB") | (us_df.MSN=="DFTCB") | (us_df.MSN=="JFTCB")
                           | (us_df.MSN=="HLTCB") | (us_df.MSN=="RFTCB") | (us_df.MSN=="P1TCB") | (us_df.MSN=="NUETB")
                           | (us_df.MSN=="HYTCB") | (us_df.MSN=="BMTCB") | (us_df.MSN=="RETCB")]
energy_types_us

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
14,2017F,US,BMTCB,1319871.0,1294762.0,1300242.0,1323316.0,1336802.0,1334761.0,1368986.0,...,3811465.0,3898016.0,4471839.0,4493640.0,4390792.0,4633408.0,4783103.0,4757010.0,4717757.0,4798494.0
48,2017F,US,CLTCB,9830513.0,9618013.0,9904585.0,10414512.0,10967543.0,11582398.0,12145291.0,...,22382816.0,19691342.0,20828382.0,19663856.0,17380923.0,18038771.0,17996577.0,15548985.0,14227138.0,13839632.0
64,2017F,US,DFTCB,3991686.0,4044624.0,4266259.0,4352755.0,4371220.0,4519117.0,4644739.0,...,8346459.0,7656512.0,8010589.0,8211183.0,7897088.0,8051055.0,8492328.0,8402506.0,8169609.0,8262728.0
132,2017F,US,HLTCB,865979.0,891189.0,973310.0,1052341.0,1124312.0,1170101.0,1234196.0,...,2655804.0,2706885.0,2884846.0,2798965.0,2892775.0,3166263.0,3066017.0,3224058.0,3177612.0,3280362.0
143,2017F,US,HYTCB,1607975.0,1656464.0,1816141.0,1771354.0,1886314.0,2059077.0,2061519.0,...,2511108.0,2668824.0,2538541.0,3102852.0,2628702.0,2562382.0,2466577.0,2321177.0,2472442.0,2766969.0
157,2017F,US,JFTCB,738522.0,826805.0,976887.0,1043682.0,1120761.0,1214502.0,1353654.0,...,3192839.0,2883274.0,2962870.0,2949817.0,2901435.0,2968557.0,3042091.0,3204168.0,3349876.0,3481346.0
199,2017F,US,MMTCB,7630802.0,7751568.0,8050790.0,8309962.0,8464411.0,8805625.0,9218658.0,...,15999412.0,15801249.0,15570293.0,15110405.0,15021605.0,15240281.0,15361358.0,15788432.0,16050927.0,16002227.0
221,2017F,US,NNTCB,12385366.0,12926392.0,13730841.0,14419107.0,15297642.0,15779457.0,17005781.0,...,23836273.0,23421003.0,24568039.0,24953771.0,26075691.0,26788768.0,27376838.0,28179686.0,28392790.0,28042043.0
224,2017F,US,NUETB,6026.0,19678.0,26394.0,38147.0,39819.0,43164.0,64158.0,...,8426491.0,8355220.0,8434433.0,8268698.0,8061822.0,8244433.0,8337559.0,8336886.0,8426753.0,8418968.0
236,2017F,US,P1TCB,3129471.0,3204314.0,3298708.0,3497534.0,3672894.0,3784081.0,3944823.0,...,5165391.0,4618088.0,4712648.0,4610774.0,4392562.0,4454535.0,4315174.0,4381315.0,4432824.0,4450985.0
295,2017F,US,RETCB,2928205.0,2952227.0,3117444.0,3096431.0,3225249.0,3395816.0,3432463.0,...,7134762.0,7566331.0,8233069.0,9088867.0,8730106.0,9235679.0,9529123.0,9493950.0,10065407.0,10895475.0
304,2017F,US,RFTCB,3517193.0,3449539.0,3431526.0,3388215.0,3486651.0,3690538.0,3938365.0,...,1431707.0,1172890.0,1227920.0,1058058.0,848525.0,731008.0,590192.0,595090.0,750655.0,784140.0

In [231]:
energy_types_us_copy = energy_types_us

In [232]:
msn_codes = {"NNTCB":"Natural Gas", "CLTCB": "Coal", "MMTCB": "Motor Gas excl Ethanol", "DFTCB": "Distillate Fuel Oil",
            "JFTCB": "Jet Fuel", "HLTCB": "HGL", "RFTCB": "Residual Fueal", "P1TCB": "Other Petroleum",
            "NUETB": "Nuclear Electric Power", "HYTCB": "Hydroelectric Power", "BMTCB": "Biomass",
            "RETCB": "Total Renewables"}

In [233]:
for key,value in msn_codes.items():
    energy_type = value
    energy_types_us_copy.loc[(energy_types_us_copy.MSN == key),'Energy_Type']=energy_type
    #print(energy_type)

In [234]:
energy_types_us_copy

,Data_Status,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
14,2017F,US,BMTCB,1319871.0,1294762.0,1300242.0,1323316.0,1336802.0,1334761.0,1368986.0,...,3898016.0,4471839.0,4493640.0,4390792.0,4633408.0,4783103.0,4757010.0,4717757.0,4798494.0,Biomass
48,2017F,US,CLTCB,9830513.0,9618013.0,9904585.0,10414512.0,10967543.0,11582398.0,12145291.0,...,19691342.0,20828382.0,19663856.0,17380923.0,18038771.0,17996577.0,15548985.0,14227138.0,13839632.0,Coal
64,2017F,US,DFTCB,3991686.0,4044624.0,4266259.0,4352755.0,4371220.0,4519117.0,4644739.0,...,7656512.0,8010589.0,8211183.0,7897088.0,8051055.0,8492328.0,8402506.0,8169609.0,8262728.0,Distillate Fuel Oil
132,2017F,US,HLTCB,865979.0,891189.0,973310.0,1052341.0,1124312.0,1170101.0,1234196.0,...,2706885.0,2884846.0,2798965.0,2892775.0,3166263.0,3066017.0,3224058.0,3177612.0,3280362.0,HGL
143,2017F,US,HYTCB,1607975.0,1656464.0,1816141.0,1771354.0,1886314.0,2059077.0,2061519.0,...,2668824.0,2538541.0,3102852.0,2628702.0,2562382.0,2466577.0,2321177.0,2472442.0,2766969.0,Hydroelectric Power
157,2017F,US,JFTCB,738522.0,826805.0,976887.0,1043682.0,1120761.0,1214502.0,1353654.0,...,2883274.0,2962870.0,2949817.0,2901435.0,2968557.0,3042091.0,3204168.0,3349876.0,3481346.0,Jet Fuel
199,2017F,US,MMTCB,7630802.0,7751568.0,8050790.0,8309962.0,8464411.0,8805625.0,9218658.0,...,15801249.0,15570293.0,15110405.0,15021605.0,15240281.0,15361358.0,15788432.0,16050927.0,16002227.0,Motor Gas excl Ethanol
221,2017F,US,NNTCB,12385366.0,12926392.0,13730841.0,14419107.0,15297642.0,15779457.0,17005781.0,...,23421003.0,24568039.0,24953771.0,26075691.0,26788768.0,27376838.0,28179686.0,28392790.0,28042043.0,Natural Gas
224,2017F,US,NUETB,6026.0,19678.0,26394.0,38147.0,39819.0,43164.0,64158.0,...,8355220.0,8434433.0,8268698.0,8061822.0,8244433.0,8337559.0,8336886.0,8426753.0,8418968.0,Nuclear Electric Power
236,2017F,US,P1TCB,3129471.0,3204314.0,3298708.0,3497534.0,3672894.0,3784081.0,3944823.0,...,4618088.0,4712648.0,4610774.0,4392562.0,4454535.0,4315174.0,4381315.0,4432824.0,4450985.0,Other Petroleum
295,2017F,US,RETCB,2928205.0,2952227.0,3117444.0,3096431.0,3225249.0,3395816.0,3432463.0,...,7566331.0,8233069.0,9088867.0,8730106.0,9235679.0,9529123.0,9493950.0,10065407.0,10895475.0,Total Renewables
304,2017F,US,RFTCB,3517193.0,3449539.0,3431526.0,3388215.0,3486651.0,3690538.0,3938365.0,...,1172890.0,1227920.0,1058058.0,848525.0,731008.0,590192.0,595090.0,750655.0,784140.0,Residual Fueal

In [235]:
final_us = energy_types_us_copy.drop(["Data_Status"], axis=1)

In [236]:
final_us.reset_index()

,index,State,MSN,1960,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Energy_Type
0,14,US,BMTCB,1319871.0,1294762.0,1300242.0,1323316.0,1336802.0,1334761.0,1368986.0,...,3898016.0,4471839.0,4493640.0,4390792.0,4633408.0,4783103.0,4757010.0,4717757.0,4798494.0,Biomass
1,48,US,CLTCB,9830513.0,9618013.0,9904585.0,10414512.0,10967543.0,11582398.0,12145291.0,...,19691342.0,20828382.0,19663856.0,17380923.0,18038771.0,17996577.0,15548985.0,14227138.0,13839632.0,Coal
2,64,US,DFTCB,3991686.0,4044624.0,4266259.0,4352755.0,4371220.0,4519117.0,4644739.0,...,7656512.0,8010589.0,8211183.0,7897088.0,8051055.0,8492328.0,8402506.0,8169609.0,8262728.0,Distillate Fuel Oil
3,132,US,HLTCB,865979.0,891189.0,973310.0,1052341.0,1124312.0,1170101.0,1234196.0,...,2706885.0,2884846.0,2798965.0,2892775.0,3166263.0,3066017.0,3224058.0,3177612.0,3280362.0,HGL
4,143,US,HYTCB,1607975.0,1656464.0,1816141.0,1771354.0,1886314.0,2059077.0,2061519.0,...,2668824.0,2538541.0,3102852.0,2628702.0,2562382.0,2466577.0,2321177.0,2472442.0,2766969.0,Hydroelectric Power
5,157,US,JFTCB,738522.0,826805.0,976887.0,1043682.0,1120761.0,1214502.0,1353654.0,...,2883274.0,2962870.0,2949817.0,2901435.0,2968557.0,3042091.0,3204168.0,3349876.0,3481346.0,Jet Fuel
6,199,US,MMTCB,7630802.0,7751568.0,8050790.0,8309962.0,8464411.0,8805625.0,9218658.0,...,15801249.0,15570293.0,15110405.0,15021605.0,15240281.0,15361358.0,15788432.0,16050927.0,16002227.0,Motor Gas excl Ethanol
7,221,US,NNTCB,12385366.0,12926392.0,13730841.0,14419107.0,15297642.0,15779457.0,17005781.0,...,23421003.0,24568039.0,24953771.0,26075691.0,26788768.0,27376838.0,28179686.0,28392790.0,28042043.0,Natural Gas
8,224,US,NUETB,6026.0,19678.0,26394.0,38147.0,39819.0,43164.0,64158.0,...,8355220.0,8434433.0,8268698.0,8061822.0,8244433.0,8337559.0,8336886.0,8426753.0,8418968.0,Nuclear Electric Power
9,236,US,P1TCB,3129471.0,3204314.0,3298708.0,3497534.0,3672894.0,3784081.0,3944823.0,...,4618088.0,4712648.0,4610774.0,4392562.0,4454535.0,4315174.0,4381315.0,4432824.0,4450985.0,Other Petroleum
10,295,US,RETCB,2928205.0,2952227.0,3117444.0,3096431.0,3225249.0,3395816.0,3432463.0,...,7566331.0,8233069.0,9088867.0,8730106.0,9235679.0,9529123.0,9493950.0,10065407.0,10895475.0,Total Renewables
11,304,US,RFTCB,3517193.0,3449539.0,3431526.0,3388215.0,3486651.0,3690538.0,3938365.0,...,1172890.0,1227920.0,1058058.0,848525.0,731008.0,590192.0,595090.0,750655.0,784140.0,Residual Fueal

In [230]:
final_us.to_csv("cleaned_energy_sources_us.csv")